import type {
  User,
  Organization,
  Category,
  Product,
  Service,
  Deal,
  Quote,
  Campaign,
  EngagementRequest,
  CreditRequest,
  Rating,
  Notification,
} from './types';

export const categories: Category[] = [
  { id: 'cat1', name: 'Networking & Infrastructure', slug: 'networking', icon: 'Network', productCount: 2450 },
  { id: 'cat2', name: 'Cloud Services', slug: 'cloud', icon: 'Cloud', productCount: 1820 },
  { id: 'cat3', name: 'Cybersecurity', slug: 'security', icon: 'Shield', productCount: 1560 },
  { id: 'cat4', name: 'Storage Solutions', slug: 'storage', icon: 'Database', productCount: 980 },
  { id: 'cat5', name: 'Software Licensing', slug: 'software', icon: 'Key', productCount: 3200 },
  { id: 'cat6', name: 'Hardware & Servers', slug: 'hardware', icon: 'Server', productCount: 1450 },
  { id: 'cat7', name: 'Professional Services', slug: 'services', icon: 'Briefcase', productCount: 890 },
  { id: 'cat8', name: 'Training & Certification', slug: 'training', icon: 'GraduationCap', productCount: 650 },
];

export const organizations: Organization[] = [
  {
    id: 'org1',
    name: 'TechDist Global',
    legalName: 'TechDist Global Inc.',
    type: 'DISTRIBUTOR',
    logo: '/logos/techdist.png',
    description: 'Leading distributor of enterprise networking and cloud solutions with 15+ years of experience.',
    industry: 'IT Distribution',
    companySize: '201-500',
    yearEstablished: 2008,
    website: 'https://techdist.satmz.com',
    verified: true,
    rating: 4.8,
    reviewCount: 245,
    address: {
      country: 'United States',
      street: '123 Tech Boulevard',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94105',
    },
    contact: {
      phone: '+1-415-555-0100',
      supportEmail: 'support@techdist.satmz.com',
      salesEmail: 'sales@techdist.satmz.com',
    },
    members: ['user1', 'user2'],
    createdAt: '2008-03-15T00:00:00Z',
  },
  {
    id: 'org2',
    name: 'NetSupply Corp',
    legalName: 'NetSupply Corporation',
    type: 'DISTRIBUTOR',
    description: 'Specialized in networking equipment and enterprise infrastructure solutions.',
    industry: 'IT Distribution',
    companySize: '51-200',
    yearEstablished: 2012,
    verified: true,
    rating: 4.6,
    reviewCount: 189,
    address: {
      country: 'United States',
      street: '456 Network Ave',
      city: 'Austin',
      state: 'TX',
      postalCode: '78701',
    },
    contact: {
      phone: '+1-512-555-0200',
      supportEmail: 'support@netsupply.satmz.com',
      salesEmail: 'sales@netsupply.satmz.com',
    },
    members: ['user3'],
    createdAt: '2012-06-20T00:00:00Z',
  },
  {
    id: 'org3',
    name: 'CloudFirst Distribution',
    legalName: 'CloudFirst Distribution LLC',
    type: 'DISTRIBUTOR',
    description: 'Your trusted partner for cloud services and SaaS solutions.',
    industry: 'Cloud Services',
    companySize: '51-200',
    yearEstablished: 2015,
    verified: true,
    rating: 4.7,
    reviewCount: 156,
    address: {
      country: 'United States',
      street: '789 Cloud Street',
      city: 'Seattle',
      state: 'WA',
      postalCode: '98101',
    },
    contact: {
      phone: '+1-206-555-0300',
      supportEmail: 'support@cloudfirst.satmz.com',
      salesEmail: 'sales@cloudfirst.satmz.com',
    },
    members: ['user4'],
    createdAt: '2015-01-10T00:00:00Z',
  },
  {
    id: 'org4',
    name: 'ABC Resellers Inc',
    legalName: 'ABC Resellers Incorporated',
    type: 'RESELLER',
    description: 'Enterprise IT solutions provider specializing in healthcare and finance sectors.',
    industry: 'IT Reseller',
    companySize: '11-50',
    yearEstablished: 2010,
    verified: true,
    rating: 4.5,
    reviewCount: 98,
    address: {
      country: 'United States',
      street: '321 Business Pkwy',
      city: 'Boston',
      state: 'MA',
      postalCode: '02108',
    },
    contact: {
      phone: '+1-617-555-0400',
      supportEmail: 'support@abcresellers.satmz.com',
      salesEmail: 'sales@abcresellers.satmz.com',
    },
    members: ['user5'],
    createdAt: '2010-09-05T00:00:00Z',
  },
  {
    id: 'org5',
    name: 'Premier Solutions Group',
    legalName: 'Premier Solutions Group LLC',
    type: 'RESELLER',
    description: 'Full-service IT reseller with focus on enterprise networking and security.',
    industry: 'IT Reseller',
    companySize: '51-200',
    yearEstablished: 2005,
    verified: true,
    rating: 4.9,
    reviewCount: 178,
    address: {
      country: 'United States',
      street: '555 Premier Way',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
    },
    contact: {
      phone: '+1-212-555-0500',
      supportEmail: 'support@premiersolutions.satmz.com',
      salesEmail: 'sales@premiersolutions.satmz.com',
    },
    members: ['user6'],
    createdAt: '2005-03-22T00:00:00Z',
  },
  {
    id: 'org6',
    name: 'Cisco Systems',
    legalName: 'Cisco Systems Inc.',
    type: 'OEM',
    description: 'Global leader in networking and security solutions.',
    industry: 'Technology',
    companySize: '10000+',
    yearEstablished: 1984,
    verified: true,
    rating: 4.9,
    reviewCount: 1250,
    address: {
      country: 'United States',
      street: '170 West Tasman Drive',
      city: 'San Jose',
      state: 'CA',
      postalCode: '95134',
    },
    contact: {
      phone: '+1-408-526-4000',
      supportEmail: 'support@cisco.com',
      salesEmail: 'partners@cisco.com',
    },
    members: ['user7'],
    createdAt: '2020-01-15T00:00:00Z',
  },
  {
    id: 'org7',
    name: 'B2B Marketplace',
    legalName: 'B2B Marketplace Platform Inc.',
    type: 'DISTRIBUTOR',
    description: 'Platform administrator organization.',
    industry: 'Technology',
    companySize: '51-200',
    yearEstablished: 2023,
    verified: true,
    rating: 5.0,
    reviewCount: 0,
    address: {
      country: 'United States',
      street: '1 Platform Way',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94102',
    },
    contact: {
      phone: '+1-415-555-9999',
      supportEmail: 'support@marketplace.satmz.com',
      salesEmail: 'sales@marketplace.satmz.com',
    },
    members: ['user8'],
    createdAt: '2023-01-01T00:00:00Z',
  },
];

export const users: User[] = [
  {
    id: 'user1',
    email: 'john@techdist.satmz.com',
    name: 'John Smith',
    organizationId: 'org1',
    role: 'ADMIN',
    createdAt: '2008-03-15T00:00:00Z',
  },
  {
    id: 'user2',
    email: 'sarah@techdist.satmz.com',
    name: 'Sarah Johnson',
    organizationId: 'org1',
    role: 'SALES_MANAGER',
    createdAt: '2010-05-20T00:00:00Z',
  },
  {
    id: 'user3',
    email: 'mike@netsupply.satmz.com',
    name: 'Mike Davis',
    organizationId: 'org2',
    role: 'ADMIN',
    createdAt: '2012-06-20T00:00:00Z',
  },
  {
    id: 'user4',
    email: 'emily@cloudfirst.satmz.com',
    name: 'Emily Wilson',
    organizationId: 'org3',
    role: 'ADMIN',
    createdAt: '2015-01-10T00:00:00Z',
  },
  {
    id: 'user5',
    email: 'robert@abcresellers.satmz.com',
    name: 'Robert Brown',
    organizationId: 'org4',
    role: 'ADMIN',
    createdAt: '2010-09-05T00:00:00Z',
  },
  {
    id: 'user6',
    email: 'lisa@premiersolutions.satmz.com',
    name: 'Lisa Anderson',
    organizationId: 'org5',
    role: 'ADMIN',
    createdAt: '2005-03-22T00:00:00Z',
  },
  {
    id: 'user7',
    email: 'david@cisco.satmz.com',
    name: 'David Martinez',
    organizationId: 'org6',
    role: 'ADMIN',
    createdAt: '2020-01-15T00:00:00Z',
  },
  {
    id: 'user8',
    email: 'admin@marketplace.satmz.com',
    name: 'Admin User',
    organizationId: 'org7',
    role: 'PLATFORM_ADMIN',
    createdAt: '2023-01-01T00:00:00Z',
  },
];

export const products: Product[] = [
  {
    id: 'prod1',
    organizationId: 'org1',
    name: 'Cisco Catalyst 9300 48-Port Switch',
    sku: 'CAT9300-48P',
    category: 'cat1',
    brand: 'Cisco',
    description: 'The Cisco Catalyst 9300 Series Switches are Cisco\'s lead stackable enterprise switching platform built for security, IoT, and cloud. They are the next generation of the industry\'s most successful switching platform.',
    shortDescription: 'Enterprise-grade 48-port stackable switch with PoE+ and advanced security features',
    price: 4999,
    currency: 'USD',
    volumePricing: [
      { minQuantity: 1, maxQuantity: 10, price: 4999, discount: 0 },
      { minQuantity: 11, maxQuantity: 50, price: 4750, discount: 5 },
      { minQuantity: 51, price: 4500, discount: 10 },
    ],
    inventory: 248,
    lowStockThreshold: 50,
    availability: 'IN_STOCK',
    leadTime: 'In Stock',
    specifications: [
      { group: 'Hardware', label: 'Port Count', value: '48', unit: 'ports' },
      { group: 'Hardware', label: 'Uplinks', value: '4x 10G/25G', unit: '' },
      { group: 'Performance', label: 'Switching Capacity', value: '440', unit: 'Gbps' },
      { group: 'Power', label: 'PoE Budget', value: '740', unit: 'W' },
      { group: 'Physical', label: 'Dimensions', value: '44.5 x 44.3 x 4.4', unit: 'cm' },
      { group: 'Physical', label: 'Weight', value: '5.9', unit: 'kg' },
    ],
    images: ['/products/cisco-catalyst-1.jpg', '/products/cisco-catalyst-2.jpg'],
    status: 'ACTIVE',
    views: 1245,
    featured: true,
    tags: ['networking', 'switch', 'enterprise', 'cisco', 'poe'],
    createdAt: '2023-01-15T10:00:00Z',
    updatedAt: '2024-01-20T15:30:00Z',
  },
  {
    id: 'prod2',
    organizationId: 'org1',
    name: 'Dell PowerEdge R750 Server',
    sku: 'DELL-R750-001',
    category: 'cat6',
    brand: 'Dell',
    description: 'The Dell PowerEdge R750 is a 2-socket 2U rack server that delivers workload optimization and resource balancing for accelerating data analytics.',
    shortDescription: '2U rack server with dual Xeon processors and enterprise features',
    price: 8999,
    currency: 'USD',
    volumePricing: [
      { minQuantity: 1, maxQuantity: 5, price: 8999, discount: 0 },
      { minQuantity: 6, maxQuantity: 20, price: 8550, discount: 5 },
      { minQuantity: 21, price: 8100, discount: 10 },
    ],
    inventory: 45,
    lowStockThreshold: 20,
    availability: 'IN_STOCK',
    leadTime: 'Ships in 3-5 days',
    specifications: [
      { group: 'Processor', label: 'CPU', value: 'Dual Intel Xeon Scalable', unit: '' },
      { group: 'Memory', label: 'RAM', value: 'Up to 8TB', unit: '' },
      { group: 'Storage', label: 'Drive Bays', value: '16', unit: 'bays' },
      { group: 'Physical', label: 'Form Factor', value: '2U', unit: '' },
    ],
    images: ['/products/dell-r750-1.jpg'],
    status: 'ACTIVE',
    views: 892,
    featured: true,
    tags: ['server', 'dell', 'enterprise', 'rack'],
    createdAt: '2023-02-10T10:00:00Z',
    updatedAt: '2024-01-18T12:00:00Z',
  },
  {
    id: 'prod3',
    organizationId: 'org2',
    name: 'Juniper EX4300 48-Port Switch',
    sku: 'JUN-EX4300-48P',
    category: 'cat1',
    brand: 'Juniper',
    description: 'High-performance Ethernet switches for enterprise access and aggregation.',
    shortDescription: 'Juniper enterprise switch with Virtual Chassis technology',
    price: 3999,
    currency: 'USD',
    volumePricing: [
      { minQuantity: 1, maxQuantity: 10, price: 3999, discount: 0 },
      { minQuantity: 11, price: 3799, discount: 5 },
    ],
    inventory: 156,
    lowStockThreshold: 50,
    availability: 'IN_STOCK',
    leadTime: 'In Stock',
    specifications: [
      { group: 'Hardware', label: 'Port Count', value: '48', unit: 'ports' },
      { group: 'Performance', label: 'Throughput', value: '176', unit: 'Gbps' },
    ],
    images: ['/products/juniper-ex4300-1.jpg'],
    status: 'ACTIVE',
    views: 678,
    featured: false,
    tags: ['networking', 'switch', 'juniper'],
    createdAt: '2023-03-20T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'prod4',
    organizationId: 'org1',
    name: 'Fortinet FortiGate 600E Firewall',
    sku: 'FORTI-600E',
    category: 'cat3',
    brand: 'Fortinet',
    description: 'Next-generation firewall with advanced threat protection and SD-WAN capabilities.',
    shortDescription: 'Enterprise firewall with AI-powered security',
    price: 15999,
    currency: 'USD',
    volumePricing: [
      { minQuantity: 1, price: 15999, discount: 0 },
    ],
    inventory: 32,
    lowStockThreshold: 15,
    availability: 'IN_STOCK',
    leadTime: 'Ships in 5-7 days',
    specifications: [
      { group: 'Performance', label: 'Firewall Throughput', value: '10', unit: 'Gbps' },
      { group: 'Performance', label: 'IPS Throughput', value: '4', unit: 'Gbps' },
      { group: 'Hardware', label: 'Interfaces', value: '16x GbE, 2x 10GbE', unit: '' },
    ],
    images: ['/products/fortinet-600e-1.jpg'],
    status: 'ACTIVE',
    views: 1024,
    featured: true,
    tags: ['firewall', 'security', 'fortinet', 'ngfw'],
    createdAt: '2023-04-05T10:00:00Z',
    updatedAt: '2024-01-22T14:00:00Z',
  },
  {
    id: 'prod5',
    organizationId: 'org2',
    name: 'HPE ProLiant DL380 Gen11 Server',
    sku: 'HPE-DL380-G11',
    category: 'cat6',
    brand: 'HP',
    description: 'World\'s best-selling server delivers security, agility, and flexibility for any workload.',
    shortDescription: '2U rack server with advanced management and security',
    price: 7499,
    currency: 'USD',
    volumePricing: [
      { minQuantity: 1, maxQuantity: 10, price: 7499, discount: 0 },
      { minQuantity: 11, price: 7124, discount: 5 },
    ],
    inventory: 67,
    lowStockThreshold: 30,
    availability: 'IN_STOCK',
    leadTime: 'In Stock',
    specifications: [
      { group: 'Processor', label: 'CPU', value: 'Intel Xeon Scalable', unit: '' },
      { group: 'Memory', label: 'Max RAM', value: '8TB', unit: '' },
      { group: 'Storage', label: 'Drive Bays', value: '24', unit: 'bays' },
    ],
    images: ['/products/hpe-dl380-1.jpg'],
    status: 'ACTIVE',
    views: 756,
    featured: false,
    tags: ['server', 'hp', 'hpe', 'proliant'],
    createdAt: '2023-05-12T10:00:00Z',
    updatedAt: '2024-01-19T11:00:00Z',
  },
  {
    id: 'prod6',
    organizationId: 'org3',
    name: 'NetApp AFF A400 All-Flash Storage',
    sku: 'NETAPP-A400',
    category: 'cat4',
    brand: 'NetApp',
    description: 'Unified all-flash storage system optimized for high-performance workloads.',
    shortDescription: 'Enterprise all-flash storage with cloud integration',
    price: 45000,
    currency: 'USD',
    volumePricing: [
      { minQuantity: 1, price: 45000, discount: 0 },
    ],
    inventory: 12,
    lowStockThreshold: 5,
    availability: 'IN_STOCK',
    leadTime: 'Ships in 7-10 days',
    specifications: [
      { group: 'Performance', label: 'IOPS', value: '400K+', unit: 'IOPS' },
      { group: 'Capacity', label: 'Max Capacity', value: '7.68', unit: 'PB' },
    ],
    images: ['/products/netapp-a400-1.jpg'],
    status: 'ACTIVE',
    views: 445,
    featured: true,
    tags: ['storage', 'netapp', 'flash', 'enterprise'],
    createdAt: '2023-06-18T10:00:00Z',
    updatedAt: '2024-01-21T16:00:00Z',
  },
];

export const services: Service[] = [
  {
    id: 'svc1',
    organizationId: 'org1',
    name: 'Managed Network Operations 24/7',
    category: 'cat7',
    description: 'Comprehensive 24/7 network monitoring and management service with proactive maintenance and rapid incident response.',
    shortDescription: 'Round-the-clock network monitoring and management',
    pricing: {
      basic: 2500,
      professional: 4500,
      enterprise: 'Custom',
    },
    deliverables: [
      '24/7 Network Monitoring',
      'Incident Response',
      'Performance Optimization',
      'Monthly Reports',
      'Capacity Planning',
    ],
    sla: '99.9% uptime guarantee with 15-minute response time',
    team: [
      {
        name: 'Tom Jenkins',
        role: 'Lead Network Engineer',
        certifications: ['CCIE', 'JNCIE'],
      },
      {
        name: 'Maria Garcia',
        role: 'Senior Network Analyst',
        certifications: ['CCNP', 'AWS Certified'],
      },
    ],
    caseStudies: [
      {
        title: 'Healthcare Network Transformation',
        industry: 'Healthcare',
        description: 'Managed network operations for 50+ hospital locations',
        metrics: ['99.99% uptime', '40% cost reduction', '60% faster incident response'],
      },
    ],
    images: ['/services/network-ops-1.jpg'],
    status: 'ACTIVE',
    views: 334,
    rating: 4.9,
    reviewCount: 67,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: 'svc2',
    organizationId: 'org3',
    name: 'Cloud Migration Services',
    category: 'cat7',
    description: 'End-to-end cloud migration planning, execution, and optimization services.',
    shortDescription: 'Seamless cloud migration with zero downtime',
    pricing: {
      basic: 5000,
      professional: 10000,
      enterprise: 'Custom',
    },
    deliverables: [
      'Assessment & Planning',
      'Data Migration',
      'Application Migration',
      'Testing & Validation',
      'Post-Migration Support',
    ],
    sla: 'Zero-downtime migration with rollback capability',
    team: [
      {
        name: 'David Chen',
        role: 'Cloud Architect',
        certifications: ['AWS Solutions Architect', 'Azure Expert'],
      },
    ],
    caseStudies: [
      {
        title: 'Enterprise SaaS Migration',
        industry: 'Finance',
        description: 'Migrated 200+ servers to AWS with zero downtime',
        metrics: ['0 downtime', '30% cost savings', '50% performance improvement'],
      },
    ],
    images: ['/services/cloud-migration-1.jpg'],
    status: 'ACTIVE',
    views: 589,
    rating: 4.8,
    reviewCount: 45,
    createdAt: '2023-02-15T10:00:00Z',
  },
];

export function initializeLocalStorage() {
  if (typeof window === 'undefined') return;

  if (!localStorage.getItem('categories')) {
    localStorage.setItem('categories', JSON.stringify(categories));
  }
  if (!localStorage.getItem('organizations')) {
    localStorage.setItem('organizations', JSON.stringify(organizations));
  }
  if (!localStorage.getItem('users')) {
    localStorage.setItem('users', JSON.stringify(users));
  }
  if (!localStorage.getItem('products')) {
    localStorage.setItem('products', JSON.stringify(products));
  }
  if (!localStorage.getItem('services')) {
    localStorage.setItem('services', JSON.stringify(services));
  }
  if (!localStorage.getItem('deals')) {
    localStorage.setItem('deals', JSON.stringify([]));
  }
  if (!localStorage.getItem('quotes')) {
    localStorage.setItem('quotes', JSON.stringify([]));
  }
  if (!localStorage.getItem('campaigns')) {
    localStorage.setItem('campaigns', JSON.stringify([]));
  }
  if (!localStorage.getItem('engagements')) {
    localStorage.setItem('engagements', JSON.stringify([]));
  }
  if (!localStorage.getItem('creditRequests')) {
    localStorage.setItem('creditRequests', JSON.stringify([]));
  }
  if (!localStorage.getItem('ratings')) {
    localStorage.setItem('ratings', JSON.stringify([]));
  }
  if (!localStorage.getItem('notifications')) {
    localStorage.setItem('notifications', JSON.stringify([]));
  }
}
